services:
  postgres:
    image: postgres:17

    environment:
      POSTGRES_USER: judgesphere
      POSTGRES_PASSWORD: judgesphere
      POSTGRES_DB: judgesphere

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: