CREATE TYPE "public"."language" AS ENUM('CPP', 'JAVA', 'PYTHON', 'JAVASCRIPT');--> statement-breakpoint
CREATE TYPE "public"."status" AS ENUM('QUEUED', 'RUNNING', 'FINISHED');--> statement-breakpoint
CREATE TYPE "public"."verdict" AS ENUM('AC', 'WA', 'TLE', 'MLE', 'CE', 'RE', 'PE', 'INTERNAL_ERROR');--> statement-breakpoint
CREATE TABLE "submissions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "submissions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"public_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"user_id" integer NOT NULL,
	"problem_id" integer NOT NULL,
	"source_code" text NOT NULL,
	"language" "language" NOT NULL,
	"status" "status" DEFAULT 'QUEUED' NOT NULL,
	"verdict" "verdict",
	"passed_testcases" integer DEFAULT 0 NOT NULL,
	"total_testcases" integer DEFAULT 0 NOT NULL,
	"runtime_ms" integer,
	"memory_kb" integer,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "submissions_public_id_unique" UNIQUE("public_id")
);
--> statement-breakpoint
ALTER TABLE "submissions" ADD CONSTRAINT "submissions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "submissions" ADD CONSTRAINT "submissions_problem_id_problems_id_fk" FOREIGN KEY ("problem_id") REFERENCES "public"."problems"("id") ON DELETE cascade ON UPDATE no action;